# Generated by Django 3.0.4 on 2020-03-17 13:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0003_auto_20200317_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserInfo',
        ),
    ]
