# Generated by Django 3.0.4 on 2020-03-17 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0004_auto_20200317_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='Profile',
        ),
    ]
