# Generated by Django 3.0.4 on 2020-03-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='desc',
            field=models.TextField(default='Hello'),
        ),
        migrations.AddField(
            model_name='destination',
            name='name',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
